<a href="https://colab.research.google.com/github/nsamuelreddy/loan_approval_prediction/blob/main/loan_approval_decisiontreeclassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
from sklearn.model_selection import train_test_split,RandomizedSearchCV
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from scipy.stats import randint
# Load the dataset directly with the correct filename
df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "architsharma01/loan-approval-prediction-dataset",
    "loan_approval_dataset.csv"  # Correct filename
)

Downloading to /root/.cache/kagglehub/datasets/architsharma01/loan-approval-prediction-dataset/versions/1/loan_approval_dataset.csv...

100%|██████████| 375k/375k [00:00<00:00, 395kB/s]

EDA

In [ ]:
 # to remove white space before column name
df.columns = df.columns.str.strip()

In [ ]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

Data Preprocessing

we will remove unecessary columns by using this  **df.drop('load_id', axis=1,inplace=True)**

In [ ]:
df.drop('loan_id',axis=1,inplace=True)

In [ ]:

print(df.head())

   no_of_dependents      education self_employed  income_annum  loan_amount  \
0                 2       Graduate            No       9600000     29900000
1                 0   Not Graduate           Yes       4100000     12200000
2                 3       Graduate            No       9100000     29700000
3                 3       Graduate            No       8200000     30700000
4                 5   Not Graduate           Yes       9800000     24200000

   loan_term  cibil_score  residential_assets_value  commercial_assets_value  \
0         12          778                   2400000                 17600000
1          8          417                   2700000                  2200000
2         20          506                   7100000                  4500000
3          8          467                  18200000                  3300000
4         20          382                  12400000                  8200000

   luxury_assets_value  bank_asset_value loan_status
0             22700000           8000000    Approved
1              8800000           3300000    Rejected
2             33300000          12800000    Rejected
3             23300000           7900000    Rejected
4             29400000           5000000    Rejected

CHANGE TEXT ROWS INTO NUMERIC ONES

In [ ]:
from sklearn.preprocessing import LabelEncoder

for col in df.select_dtypes(include="object").columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [ ]:
df.corr()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
no_of_dependents,1.000000,-0.002697,0.000765,0.007266,-0.003366,-0.020111,-0.009998,0.007376,-0.001531,0.002817,0.011163,0.018114
education,-0.002697,1.000000,0.023224,-0.011625,-0.010631,0.008417,0.004649,-0.010930,0.006763,-0.012471,-0.009424,0.004918
self_employed,0.000765,0.023224,1.000000,0.002368,0.001450,0.004107,-0.004866,0.006144,-0.017998,0.004413,-0.000215,-0.000345
income_annum,0.007266,-0.011625,0.002368,1.000000,0.927470,0.011488,-0.023034,0.636841,0.640328,0.929145,0.851093,0.015189
loan_amount,-0.003366,-0.010631,0.001450,0.927470,1.000000,0.008437,-0.017035,0.594596,0.603188,0.860914,0.788122,-0.016150
loan_term,-0.020111,0.008417,0.004107,0.011488,0.008437,1.000000,0.007810,0.008016,-0.005478,0.012490,0.017177,0.113036
cibil_score,-0.009998,0.004649,-0.004866,-0.023034,-0.017035,0.007810,1.000000,-0.019947,-0.003769,-0.028618,-0.015478,-0.770518
residential_assets_value,0.007376,-0.010930,0.006144,0.636841,0.594596,0.008016,-0.019947,1.000000,0.414786,0.590932,0.527418,0.014367
commercial_assets_value,-0.001531,0.006763,-0.017998,0.640328,0.603188,-0.005478,-0.003769,0.414786,1.000000,0.591128,0.548576,-0.008246
luxury_assets_value,0.002817,-0.012471,0.004413,0.929145,0.860914,0.012490,-0.028618,0.590932,0.591128,1.000000,0.788517,0.015465
bank_asset_value,0.011163,-0.009424,-0.000215,0.851093,0.788122,0.017177,-0.015478,0.527418,0.548576,0.788517,1.000000,0.006778
loan_status,0.018114,0.004918,-0.000345,0.015189,-0.016150,0.113036,-0.770518,0.014367,-0.008246,0.015465,0.006778,1.000000

In [ ]:
df.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [ ]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   no_of_dependents          4269 non-null   int64
 1   education                 4269 non-null   int64
 2   self_employed             4269 non-null   int64
 3   income_annum              4269 non-null   int64
 4   loan_amount               4269 non-null   int64
 5   loan_term                 4269 non-null   int64
 6   cibil_score               4269 non-null   int64
 7   residential_assets_value  4269 non-null   int64
 8   commercial_assets_value   4269 non-null   int64
 9   luxury_assets_value       4269 non-null   int64
 10  bank_asset_value          4269 non-null   int64
 11  loan_status               4269 non-null   int64
dtypes: int64(12)
memory usage: 400.3 KB

(4269, 12)

In [ ]:
df.isnull().sum()

no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [ ]:
df.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

Data division

In [ ]:
x=df.drop('loan_status' , axis =1)
y=df['loan_status']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

Model Training

In [ ]:
model=DecisionTreeClassifier()
params={
    'max_depth': randint(3,20),
    'min_samples_split':randint(2,20),
    'min_samples_leaf': randint(1,9),
    'criterion':['gini','entropy']
}

RandomizedSearch

In [ ]:
random=RandomizedSearchCV(
    estimator=model,
    cv=5,
    param_distributions=params,
    n_iter=10,
    scoring='accuracy',
    random_state=20
)

In [ ]:
random.fit(x_train,y_train)
print("Best parameters are ",random.best_params_)
print("Best score ",random.best_score_)
best_model=random.best_estimator_
y_pred=best_model.predict(x_test)
print(accuracy_score(y_test,y_pred))

Best parameters are  {'criterion': 'entropy', 'max_depth': 19, 'min_samples_leaf': 6, 'min_samples_split': 8}
Best score  0.9812591508052708
0.9859484777517564

Confusion Matrix

In [ ]:
confusion=confusion_matrix(y_test,y_pred)
confusion

array([[531,   5],
       [  7, 311]])

In [ ]:
classificationreport = classification_report(y_test,y_pred)
classificationreport

'              precision    recall  f1-score   support\n\n           0       0.99      0.99      0.99       536\n           1       0.98      0.98      0.98       318\n\n    accuracy                           0.99       854\n   macro avg       0.99      0.98      0.98       854\nweighted avg       0.99      0.99      0.99       854\n'

In [ ]:
importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": best_model.feature_importances_
})


print(importance)

print("Accuracy  is ",accuracy_score)

                     Feature  Importance
0           no_of_dependents    0.003167
1                  education    0.000000
2              self_employed    0.000000
3               income_annum    0.034821
4                loan_amount    0.038333
5                  loan_term    0.127346
6                cibil_score    0.773474
7   residential_assets_value    0.012986
8    commercial_assets_value    0.004652
9        luxury_assets_value    0.003360
10          bank_asset_value    0.001861
Accuracy  is  <function accuracy_score at 0x791a13af0e00>

In [ ]:
import joblib
joblib.dump(best_model, "loan_approval_decision_tree.pkl")

['loan_approval_decision_tree.pkl']

In [ ]:
df.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')